version: '3.8'
networks:
  app-network:
    driver: bridge
    name: app-network

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - db-movie:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db-movie:
    name: db-movie
